version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: shoes/catalogapi
    build: 
      context: ./ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      DatabaseServer: mssqlserver
      DatabaseName: Catalogdb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalDomainUrl: http://localhost:5030
      AllowHosts: "*"
    container_name: catalogapi
    ports:
     - "5030:80"
    networks:
     - backend
     - frontend
    depends_on:
     - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    ports:
     - "1445:1443"
    container_name: mssqlcontainer
    environment:
     ACCEPT_EULA: Y
     SA_PASSWORD: ProductApi(!)
    networks:
     - backend

  catalogfe:
    build: 
      context: ./webmvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      CatalogUrl: http://catalog
      ExternalDomainUrl: http://localhost:5031
    container_name: catalogfe
    ports:
     - "5031:80"
    networks:
     - frontend
    depends_on:
     - catalog
